id: P009349
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23850
  title: གཏམ་པདྨའི་ཚལ་གྱི་ཟློས་གར།
  author: ''
  volumes:
    e7531b18462142e4bb22c5c07ed445ab:
      image_group_id: I1KG24063
      title: ''
      volume_number: 1
      total_pages: 76
