id: P009349
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:34:37.612734
source_metadata:
  id: bdr:W1KG23850
  title: གཏམ་པདྨའི་ཚལ་གྱི་ཟློས་གར།
  author: ''
  volumes:
    e7531b18462142e4bb22c5c07ed445ab:
      image_group_id: I1KG24063
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
