id: I404BADD7
legacy_id: P009349
ocr_import_info:
  bdrc_scan_id: W1KG23850
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T23:19:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:31:11.193078+00:00'
last_modified: 2022-08-27 15:31:22.386717
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG23850
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG23850
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏམ་པདྨའི་ཚལ་གྱི་ཟློས་གར།
  author: རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8715834003956435
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG24063:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24063
      total_pages: 76
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24063.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8715834003956435
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
