id: I404BADD7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:19:33+00:00'
last_modified: '2022-06-08T10:23:06.835902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23850
  title: གཏམ་པདྨའི་ཚལ་གྱི་ཟློས་གར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CE44:
      image_group_id: I1KG24063
      title: ''
      total_pages: 76
      order: 1
      base_file: CE44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
